import type { Metadata } from "next";
import { Lato, Outfit } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-lato",
  subsets: ["latin"],
});

const outfit = Outfit({
  weight: ["100","200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.variable} ${outfit.variable} antialiased`}>
        {children}
        
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
